<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SurfWeb.ServerStatus</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\SurfWeb.Services.csproj" />
    <ProjectReference Include="..\SurfWeb.Core\SurfWeb.Core.csproj" />
    <ProjectReference Include="..\Utils\Utils.csproj" />
  </ItemGroup>

</Project>
